dragonfly/session/session.go

Allows the player to transfer to other dimensions

Added dimension transfer

---

dragonfly/player/handler.go
dragonfly/player/player.go
dragonfly/server.go
dragonfly/world/handler.go
dragonfly/world/provider.go
dragonfly/world/world.go

This merge request adds a world package with some basic structure. The worlds currently have no functionality.

World package

---

dragonfly/session/session.go

Basic scoreboard sending and removing, this has no API at the moment

Created basic scoreboard sending and removing

---

dragonfly/player/handler.go
dragonfly/player/player.go
dragonfly/player/scoreboard/scoreboard.go
dragonfly/session/session.go
dragonfly/session/text.go

This pull request implements scoreboards. The API is very simple, allowing a title of the scoreboard and a number of lines.

Scoreboard implementation

---

dragonfly/player/bossbar/bossbar.go
dragonfly/player/player.go
dragonfly/player/title/title.go
dragonfly/session/session.go
dragonfly/session/text.go

This merge request implements boss bar sending and removal.

Boss bar implementation

---

dragonfly/block/diamond_block.go
dragonfly/block/register.go

just a small contribution to get into it.

Added Diamondblock

---

dragonfly/block/register.go
dragonfly/block/sponge.go

Implement sponge block

---

dragonfly/block/glazed_terracotta.go
dragonfly/block/register.go
dragonfly/block/sponge.go
dragonfly/block/stained_terracotta.go
dragonfly/block/terracotta.go

This PR adds the stained and the glazed terracotta blocks and removes my forgotten TODO in the sponge source file.

Implement terracotta and glazed terracotta

---

dragonfly/block/hashes.go
dragonfly/block/register.go
dragonfly/block/trapdoor.go

This PR implements trapdoors to Dragonfly

Implemented trapdoors

---

dragonfly/block/ancient_debris.go
dragonfly/block/break_info.go
dragonfly/block/coal_ore.go
dragonfly/block/diamond_ore.go
dragonfly/block/emerald_ore.go
dragonfly/block/gold_ore.go
dragonfly/block/hashes.go
dragonfly/block/iron_ore.go
dragonfly/block/lapis_ore.go
dragonfly/block/nether_gold_ore.go
dragonfly/block/register.go
dragonfly/item/coal.go
dragonfly/item/gold_nugget.go
dragonfly/item/register.go

* Coal Ore
* Iron Ore
* Gold Ore
* Nether Gold Ore
* Lapis Lazuli Ore
* Diamond Ore
* Emerald Ore
* Ancient Debris
* Coal
* Gold Nuggets

Added various ores

---

dragonfly/player/form/menu.go

Implements the WithButtons() method to form.Menu to allow for dynamic buttons

Implement dynamic Menu forms

---

dragonfly/session/world.go
dragonfly/world/particle/block.go
go.mod

It's a simple change, I needed it for my project :p
lemme know if i should change the description, it might be incorrect

implement evaporate particle

---

dragonfly/block/beetroot_seeds.go
dragonfly/block/carrot.go
dragonfly/block/leaves.go
dragonfly/block/melon_seeds.go
dragonfly/block/potato.go
dragonfly/block/pumpkin_seeds.go
dragonfly/block/wheat_seeds.go

Should've gotten everything, let me know if I missed everything. 
Also set the rand.Rand instance to a _ when not required.

Makes several RandomTicker block implementations use the rand.Rand instance provided

---

server/server.go

server/server.go: Support player capes.

---

server/block/block.go
server/block/dirt.go
server/block/double_flower.go
server/block/double_tall_grass.go
server/block/flower.go
server/block/grass.go
server/block/nether_sprouts.go
server/block/register.go
server/block/tall_grass.go

Implemented Soil interface

---

server/session/world.go
server/world/viewer.go
server/world/world.go

Send world spawn to players when necessary

---

server/player/player.go

The problem is described in the title
The whole problem is the extra "!" :clown_face:

Animation a block breating after hitting a block with a sword 

---

server/player/form/submit.go
server/session/handler_modal_form_response.go

Code has shitty doc please fix doc

Form close detection

---

server/player/handler.go
server/player/player.go
server/session/controllable.go
server/session/handler_level_sound_event.go

This allow you to handle when a player punches  the air

New player handler: HandlePunchAir

---

server/player/form/menu.go
server/session/handler_modal_form_response.go

Patch players being kicked when submitting a menu form

---

server/player/scoreboard/scoreboard.go
server/session/text.go

this pr add a new function to replace lines in the scoreboard

Allow replacing lines in the scoreboard

---

.gitignore
config.toml
server/config.go
server/server.go

https://github.com/df-mc/dragonfly/issues/255

Enables resource pack loading in Dragonfly

---

server/player/player.go

fix disconnecting without respawning

---

server/event/context.go

add a context.Cancelled() method

---

server/entity/action/action.go
server/player/handler.go
server/player/player.go
server/session/world.go

Implement critical hits

---

server/player/player.go

The method was there in session but it was never added to player

Add a method to send a jukebox popup to Player

---

server/block/dragon_egg.go

in this issue, you can't break the dragon egg, even in creative

this should fix issue #391

---

server/player/player.go
server/session/entity_metadata.go

This adds the following methods to Player: SetScoreTag, ScoreTag

Implement Scoretags

---

server/world/handler.go
server/world/world.go

Add a HandleEntitySpawn and HandleEntityDespawn

---

server/session/world.go
server/world/sound/entity.go

add experience/levelup sounds

---

server/player/player.go

falling into the void and respawning keeps a player's fall distance, thus making them die once more of fall damage

player/player.go: fix bug when respawning

---

server/world/weather.go

I think it should do what it says on the label.

Really start the weather.

---

server/entity/experience.go

Allow for a more visually accurate progress bar.

---

server/entity/effect.go

Update the entity state when effects expire

---

server/block/fletching_table.go
server/block/hash.go
server/block/register.go

Addition of the fletching table block.
This time, without a bunch of other files. Once again, I forgot about my warning to avoid using "git add ."
Documentation included.

Added fletching table block

---

server/player/handler.go
server/player/player.go

Keep Inventory

---

server/cmd/command.go
server/cmd/doc.go
server/cmd/parameter.go
server/doc.go
server/item/register.go
server/item/stack.go

Non functional changes to the code caused by running `go fmt ./...` on it.
@Sandertv

Golang 1.19.x formatting.

---

server/player/player.go

This is for vanilla parity.
This is my first time doing something in go! :D

Do not show effect particles when wearing the turtle helmet

---

server/world/biome/register.go
server/world/biome/windswept_forest.go

Aka extreme_hills_plus_trees, Adding biome ID 34.

Windswept Forest.

---

server/world/biome/register.go
server/world/biome/windswept_gravelly_hills.go
server/world/biome/windswept_hills.go

I found some more biomes not previously covered (extreme_hills and extreme_hills_mutated).

world/biome: Added the Windswept Hills and Gravelly Hills biomes.

---

server/player/player.go

Due a mistake i had to make a new PR...

Fix spectors able to pick up items from the floor *spectators

---

server/block/sponge.go

issue: https://github.com/df-mc/dragonfly/issues/726

Wet sponge now dries out in nether

---

server/session/handler_interact.go

Fixes #769.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#769: Inventory issue](https://oss.issuehunt.io/repos/206809182/issues/769)
---
</details>

Fixed inventories not opening under sub chunk request system

---

server/world/biome/cherry_grove.go
server/world/biome/register.go

world/biome: Added the Cherry Grove biome.

---

server/session/world.go
server/world/viewer.go

This allows custom entities to send custom animations as well.

viewer: ViewEntityAnimation

---

server/block/decorated_pot.go

Fix dropping decorated pot

---

server/world/chunk/chunk.go
server/world/chunk/sub_chunk.go

This allows for two chunks with two different pointers to still be compared for equality. (TAKE 2)

Added function to compare chunks (TAKE 2) (Ethan seems to be dead)

---

server/entity/firework_behaviour.go

Fix https://github.com/df-mc/dragonfly/issues/790

Fix panic when using fireworks with elytra

---

server/block/grindstone.go

Fix for #728 
Works as intended in vanilla now.

Fix Grinstones

---

server/session/chunk.go

send dimension id on LevelChunk packet

---

server/item/inventory/inventory.go

Set item to air when removing an item

---

server/session/world.go

This PR fixes the behaviour of the player skin
Prior to this fix, other players who are not viewers of the player who had their skin changed did not receive a skin update
https://github.com/df-mc/dragonfly/blob/99f2abbe63701d902832443dd951f0af6d90334c/server/player/player.go#L247

Fix player skin rendering

---

server/player/type.go

Fixes players falling under blocks
Reference: https://github.com/pmmp/PocketMine-MP/blob/09bf203267aca9b83a09640e17bfac0fc7b58ff8/src/entity/Human.php#L528

player/type.go: fix network offset

---

server/player/conf.go

xuid is currently not being initialize

Initialize XUID

---

server/entity/effect/fire_resistance.go
server/entity/effect/instant_damage.go
server/entity/effect/invisibility.go
server/entity/effect/jump_boost.go
server/entity/effect/night_vision.go
server/entity/effect/poison.go
server/entity/effect/resistance.go
server/entity/effect/slow_falling.go
server/entity/effect/slowness.go
server/entity/effect/speed.go
server/entity/effect/water_breathing.go
server/entity/effect/wither.go
server/item/book_and_quill.go
server/item/bottle_of_enchanting.go
server/item/lingering_potion.go
server/item/splash_potion.go

Fix splash and lingering potions and bottle o' enchanting

---

server/item/crossbow.go

This pr modify's the velocity a firework shoots from a crossbow.

Crossbow Firework shoot

---

server/internal/iteminternal/components.go

this pr removes the render_offsets it was deprecated a few versions back 
resolves #799

remove deprecated render_offsets

---

server/session/player.go

This fixes FoV and speed issues.

session/player.go: don't send actual walk speed via UpdateAbilities

---

server/entity/effect.go

fix effects #1016

---

server/entity/effect.go
server/entity/effect/effect.go
server/player/playerdb/effect.go
server/player/playerdb/json.go
server/session/player.go

old pr got deleted by accident :sob:

Added infinite effects

---

server/session/world.go

Source: https://github.com/pmmp/BedrockProtocol/blob/master/src/types/ParticleIds.php

Fix incorrect particle ids

---

server/player/player.go

Fix fall damage when sprinting down stairs
