df-mc/dragonfly

dragonfly/player/player.go
dragonfly/player/skin/cape.go
dragonfly/player/skin/skin.go
dragonfly/server.go
go.mod

This merge request adds API to get the skin from a player. It provides a Skin and Cape type, both of which implement the image.Image interface so that they may be directly encoded as an image.

Implemented player skins

---

dragonfly/session/session.go
dragonfly/world/chunk/block_storage.go
dragonfly/world/chunk/chunk.go
dragonfly/world/chunk/data.go
dragonfly/world/chunk/palette.go
dragonfly/world/chunk/position.go
dragonfly/world/chunk/sub_chunk.go

This merge request adds a `chunk` package which implements chunks. Chunks themselves are rather low-level abstract structures: They don't work directly with blocks, but instead only with block runtime IDs.
The main structure of a chunk is as follows:
Chunk:
0-16 Sub chunks:
0-256 Block storages:
Runtime ID palette
Pointers to the palette, representing blocks
The block storages of each sub chunk hold a palette, which in turn holds all block runtime IDs used in that storage. The storage then has 4096 pointers to runtime IDs in that palette. The size of these pointers varies, depending on how many unique blocks there are in the palette. They will have a size of either 1, 2, 3, 4, 5, 6, 8 or 16 bits, where the sizes 3, 5 and 6 have additional padding.

Implemented basic chunks and chunk sending

---

dragonfly/player/player.go
dragonfly/server.go
dragonfly/session/world.go
dragonfly/world/mcdb/provider.go
dragonfly/world/provider.go
dragonfly/world/viewer.go
dragonfly/world/world.go

This PR implements time in Dragonfly: There is now API for time changing and stopping, and Dragonfly will, by default, have a working day-night cycle. These properties are also saved to the provider.

Time implementation

---

server/player/provider.go

Fixes #202
This happened after changing `Load(UUID uuid.UUID) (Data, bool)` to `Load(UUID uuid.UUID) (Data, error)`. The player provider sends empty data but also no error so all these nil values will get assigned to the player.

Fix a player goroutine blocking when the provider is disabled

---

server/block/beacon.go

You said that items or blocks have to implement the [UsableOnBlock](https://github.com/df-mc/dragonfly/blob/e0ae99eaf1c2b57ad829f7cc186dd70efbf71ecb/server/item/item.go#L21) interface when they have special logic on interaction. However, I couldn't find the "special logic" of the beacon block.
https://github.com/df-mc/dragonfly/blob/e0ae99eaf1c2b57ad829f7cc186dd70efbf71ecb/server/block/beacon.go#L35-L44
I looked into the source code of the beacon block and asked "aren't all blocks can replace a replaceable block" in Bedrock Gophers Discord. Pig told me that this probably is a leftover code.

Leftover code? block.Beacon.UseOnBlock()

---

server/player/chat/chat.go

Made a few changes to chat.Chat
Converted Chat.subscriber from a slice into a map for:
- Prevent duplicated subscriber if subscribe is already subscribed
- Easier access to checking and removing subscriber
Added Chat.Subscribed():
- Allows checking if a subscriber subscribed to the chat, or not
- While this is unnecessary if there was only one chat, when juggling with multiple chats, it helps to be able to check and to display as user feedback

Minor improvements toward the usability of chat.Chat

---

server/player/form/form.go
server/player/form/menu.go
server/player/form/modal.go
server/player/form/submit.go
server/session/handler_modal_form_response.go

Sorry, I did a small mistake. The code checks if a `form.Form` struct is a Closer, instead of the submittable of it.

Fixed form close detection not working

---

server/player/player.go
server/session/player.go

Vanilla's instant respawn is client-side, it just removes the respawn screen which is why this works.

Adds the option to enable vanilla instant respawn

---

server/player/handler.go
server/player/player.go

This PR makes it possible to alter what items are dropped when a block is mined by a player.

add a drops parameter to HandleBlockBreak

---

server/session/session.go

As the title.
Tested, it works(HandleQuit)

session/session.go: fix player.Close not called correctly

---

server/block/quartz_block.go

Block of quartz, chiseled quartz block and smooth quartz block wouldn't show up in the creative inventory.
It was caused by the code registering those blocks facing the `x` axis, and the "`x` axis facing" variants of those blocks wouldn't show up in the creative inventory.
It was fixed by just changing the `pillar_axis` value of those blocks to `y`.

Fixed some quartz blocks not appearing in the creative inventory

---

server/player/player.go

Should it maybe panic if it does not start with a "/", since i dont think there is any case where it should. I was personally confused as to why my command was not recognised so I felt like this might be an important thing to add to the documentation.

player.go: make ExecuteCommand doc slightly more clear

---

server/session/chunk.go

Enable the sub-chunk request system because Mojang can't do anything right.

---

server/block/sugar_cane.go

Lava could unintentionally break the check for water early.

Fix short circuit logic.

---

server/internal/iteminternal/components.go
server/world/item.go

With this PR you can correct the item scale. (It's more like modifying item render position. But there is a component which can set the position/rotation of custom item)
(Originally from my [CustomItemLoader](https://github.com/alvin0319/CustomItemLoader/blob/master/src/alvin0319/CustomItemLoader/item/properties/CustomItemProperties.php#L674-#L708) for PocketMine-MP)
The following images are showing the difference between non-render_offsets item and render_offsets item.
(This item has 32x32 width/height.)
Before this PR:
After this PR:

Implement partial render_offsets (scale) component

---

server/conf.go

When creating a `server.Config` from a `server.UserConfig` via `server.UserConfig.Config()`,  a persistent world provider (via `mcdb.New()`) is always created — there is no way to make use of `world.NopProvider` .
This PR addresses this lack by adding a new attribute `UserConfig.World.SaveData` , and updates `server.UserConfig.Config()` to honor it.
For consistency, this change matches the way `PlayerProvider` configuration is already implemented.

Update configuration interface so the Nop world provider can optionally be used

---

server/world/mcdb/provider.go

With "ioutil" being deprecated in Golang 1.16+ this replaces it with calls to "os".

Remove last ioutil usage.

---

server/block/deepslate.go

Deepslate can only be obtained by mining it using a pickaxe with the Silk Touch enchantment, otherwise it drops cobbled deepslate.

Silk touch for deepslate type

---

server/player/player.go

In case you break the chest, all items in the chest that assigned to the drops variable got reassigned by drops of the current block.

Fix incorrect drops

---

server/block/ender_chest.go

Discovered this creating a structure, on paste, all the enderchest were facing in the same direction, this fixed it.

fix enderchest facing direction not being decoded

---

server/session/session.go

As discussed on Discord, it appears that the client is now more strict with client cache.
Fixes #853

Fix Client Cache issues

---

server/block/blast_furnace.go
server/block/furnace.go
server/block/lectern.go
server/block/smoker.go

- Fixes #833
This happend because a furnace(or other blocks) can only face horizontally but cube.Face default is down so an error occured so we are using cube.Direction now for the Facing.

Fix for horizontally facing blocks

---

server/entity/lingering_potion.go
server/entity/splash_potion.go

Since potion-related(splash and lingering) items don't have a glint in the current version of the game, entities shouldn't have one either

Removed the splash and lingering potion entity glint

---

server/item/stack.go

This PR adds the WithoutArmourTrim func and fixes an issue with ArmourSmithingTemplateFromString func not having the rib template

implement a way to remove armour trims + bug fix with trims

---

go.mod
go.sum
server/session/entity_metadata.go

With the new version 1.21, mob effect bubbles are no longer int32-packed RGBA. Now it is an array of bytes up to 8 elements packed in int64.
Before: https://youtu.be/k1qiewknQwQ
After: https://youtu.be/YI8ETqjhow0
https://github.com/sandertv/gophertunnel must be updated with the new entity metadata key.

Implemented a new way of displaying the mob effects.

---

server/session/entity_metadata.go

The implementation has the following problems:
- Does not include ambient indicator
- Only the first two effects are correctly packed
- This is caused because for some reason you are multiplying the shift 7 by the index. (wtf??).
-  On the first iteration nothing happened because it gave a bit shift of 0, as it is the first iteration it does not matter if there is bit shift or not.
- On the second iteration 7 * 1, the shift is correct, Ok
- From the third iteration on, the shifts are incorrect.
`I almost had a stroke with the go syntax`

entity_metadata.go: Fix incorrectly enconding of packedEffects

---

server/block/ladder.go
server/block/model/ladder.go

Fixed a bug where ladder wasn't being added to creative inventory. It was happening due to ladder in dragonfly not allowing facing_direction to be 0 and 1. We already discussed this in Discord:

block/ladder.go: Change Direction to Face to allow states 0 and 1

---

server/session/player.go

There's no way to tell if a player can see an entity or not, so if you call player.ShowEnitty() and the player can already see the entity it will cause some issues & race conditions

Avoid Showing/hiding entities unconditionally

---

server/block/composter.go

In vanilla, hopper can insert item in composter only if it's level is less than 7

Fixed hopper insert behaviour in composter

---

go.mod
go.sum
server/block/ender_chest.go
server/player/player.go
server/server.go
server/session/handler_anvil.go
server/session/handler_beacon.go
server/session/handler_enchanting.go
server/session/handler_grindstone.go
server/session/handler_item_stack_request.go
server/session/handler_loom.go
server/session/handler_modal_form_response.go
server/session/handler_player_auth_input.go
server/session/handler_server_bound_loading_screen.go
server/session/player.go
server/session/session.go
server/session/text.go
server/session/world.go
server/world/conf.go
server/world/settings.go
server/world/world.go

[df-mc/atomic](https://github.com/df-mc/atomic) was forked with the release of generics to add atomic.Value[T], and since Go 1.19 everything we used [uber-go/atomic](https://github.com/uber-go/atomic) for has since been implemented in some form in `sync/atomic`. This PR removes the `df-mc/atomic` dependency and that repo will be archived when this is merged.

Migrate from df-mc/atomic to sync/atomic

---

server/player/form/element.go

> // Default is the default value filled out in the input. The user may remove this value and fill out its
// own text. The text may contain Minecraft formatting codes.
This was likely copied over from the Input's default field.
I discovered this while reading df's form implementation to help implement and especially document my own in Rust. (Thanks for all the comments in both df and gophertunnel, they are really helpful and I did not copy the comments 1:1 for the record)
This is a giant pr, so be warned!

Documentation correction: Toggles dont contain text as far as I know

---

server/item/enchantment/flame.go

The flame duration has changed from some version to five seconds

enchantment/flame.go: Arrow flame duration is always five seconds

---

server/entity/item_behaviour.go
server/entity/projectile.go
server/player/player.go

strictly remove arrow if it has been picked up

---

config.toml
server/cmd/argument.go
server/cmd/command.go
server/cmd/output.go
server/conf.go
server/player/chat/chat.go
server/player/chat/subscriber.go
server/player/chat/translate.go
server/player/player.go
server/server.go
server/session/command.go
server/session/session.go
server/session/text.go

PR implements a system for client-side translations. Additionally, this message can be plugged into easily for server-side translations too.

(Client-side) translation system

---

server/player/player.go

* [`server/player/player.go`](diffhunk://#diff-826d2b8b93662b774ba65460276a04857b96d6e04bf4c95d12958b42f1189ff9L2315-R2315): Modified the `HideEntity` method to compare the unique identifiers of the player and the entity to prevent the player from hiding itself.

player.HideEntity checks EntityHandle, prevent the player from hiding itself

---

server/session/player.go

- It allows showing hotbar, opening menus, etc. 
Servers usually allow players to use an item in spectator mode. For example, players might want to use a compass item to teleport. This is not possible when the hotbar is not visible.
- It's possible to hide the hotbar via SetHudPacket, but it won't be implemented in this PR.

Spectator Mode use GameTypeSurvivalSpectator

---

server/world/mcdb/leveldat/data.go

adds locatorbar to world data
fixes 
open db: unmarshal level.dat: level.dat: decode nbt: nbt: unexpected named tag '.locatorbar' with type TAG_Byte at offset 2040: not present in struct to be decoded into

update world data

---

server/item/stack.go

```go
a := item.NewStack(item.Feather{}, 1)
a = a.WithValue("x", 1)
a = a.WithValue("x", nil) // x is removed here
b := item.NewStack(item.Feather{}, 1)
a.Comparable(b) // false, this should return true
```

item/stack.go: WithValue set data to nil when data len is zero

---

go.mod
go.sum
server/player/debug/renderer.go
server/player/debug/shape.go
server/player/player.go
server/session/controllable.go
server/session/player.go
server/session/session.go

Implements full coverage of the new debug drawer functionality, with batching. Shapes are added to add/remove queues until the next tick where all the pending actions are sent to the client.
Rotation does nothing when provided for any shape, so it has been omitted.
Duration does nothing when provided for any shape, so it has been omitted.
Arrows, Boxes, Circles, Lines, Spheres & Text can be created. Text supports any RGBA colour (for the whole line), and may be a suitable replacement for Dragonfly's floating text option.
Example for adding a red sphere with 100 segments:
```go
p.AddDebugShape(&debug.Sphere{
Colour: color.RGBA{R: 255, A: 255},
Position: p.Position(),
Segments: 100,
})```

player/debug: Add support for new debug drawing

---

server/item/arrow.go
server/item/firework.go
server/item/inventory/armour.go
server/item/inventory/inventory.go
server/item/nautilus_shell.go
server/item/totem.go
server/player/type.go

It would be useful to know if you can put item in the offhand
Ps:
maybe I miss some items

implement item.OffHand to offhand items

---

server/player/player.go

sometimes you just fails to place block, maybe it because of floating point error or something else (it mostly noticeable with very low z axis), but increasing the epsilon fixes this problem without any consequences
The problem:
https://github.com/user-attachments/assets/d8184c4d-5d9f-49f1-b02f-860d12d44672

fix block placing near the player

---

server/player/player.go

currently players with nil session would cause nil panic (NPE), this PR dedicated to fix that.

Fix: Use p.session() instead of p.s for debug shape.

---

server/server.go

This pull request addresses an issue where custom block items were not rendering correctly when dropped in the world or held in the inventory. Previously, these items would appear as an invisible item.

Fix: Custom Block Items Not Rendering Correctly
